{
  "Header": {
    "Original": "CVE-2025-9394 (A flaw has been found in PoDoFo 1.1.0-dev. This issue affects the func ...)",
    "ID": "CVE-2025-9394",
    "Description": "(A flaw has been found in PoDoFo 1.1.0-dev. This issue affects the func ...)"
  },
  "Annotations": [
    {
      "Original": "- libpodofo \u003cnot-affected\u003e (Vulnerable code introduce later)",
      "Type": "package",
      "Package": "libpodofo",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduce later"
    },
    {
      "Original": "NOTE: https://github.com/podofo/podofo/issues/275",
      "Type": "NOTE",
      "Description": "https://github.com/podofo/podofo/issues/275"
    },
    {
      "Original": "NOTE: https://github.com/podofo/podofo/commit/22d16cb142f293bf956f66a4d399cdd65576d36c",
      "Type": "NOTE",
      "Description": "https://github.com/podofo/podofo/commit/22d16cb142f293bf956f66a4d399cdd65576d36c"
    }
  ]
}